export type SeedProduct = {
  slug: string;
  name: string;
  brand: string;
  category: "food" | "accessories" | "toys" | "litter" | "grooming" | "pharmacy";
  petTypes: string[];
  price: number;
  oldPrice?: number;
  unit: string;
  stock: number;
  lowStockAt: number;
  image: string;
  blurb: string;
};

/** Local prices are estimates in PKR; shop can correct them in the admin panel. */
export const SEED_PRODUCTS: SeedProduct[] = [
  {
    slug: "royal-canin-persian-adult-2kg",
    name: "Royal Canin Persian Adult",
    brand: "Royal Canin",
    category: "food",
    petTypes: ["cat"],
    price: 7400,
    unit: "2 kg bag",
    stock: 6,
    lowStockAt: 3,
    image: "/images/food/cat-food-1.jpg",
    blurb: "Almond-shaped kibble the Persian can pick up easily. For adults 1 to 7 years.",
  },
  {
    slug: "royal-canin-shih-tzu-adult-15kg",
    name: "Royal Canin Shih Tzu Adult",
    brand: "Royal Canin",
    category: "food",
    petTypes: ["dog"],
    price: 6900,
    unit: "1.5 kg bag",
    stock: 5,
    lowStockAt: 3,
    image: "/images/food/dog-food-1.jpg",
    blurb: "Wave-shaped kibble for the Shih Tzu underbite. Skin and coat support.",
  },
  {
    slug: "whiskas-adult-chicken-13kg",
    name: "Whiskas Adult Chicken",
    brand: "Whiskas",
    category: "food",
    petTypes: ["cat"],
    price: 21500,
    oldPrice: 23500,
    unit: "13 kg sack",
    stock: 4,
    lowStockAt: 2,
    image: "/images/food/cat-food-2.jpg",
    blurb: "Bulk sack that keeps a multi-cat home fed for weeks. Chicken flavour.",
  },
  {
    slug: "josera-kitten-10kg",
    name: "Josera Kitten",
    brand: "Josera",
    category: "food",
    petTypes: ["cat"],
    price: 18900,
    unit: "10 kg sack",
    stock: 3,
    lowStockAt: 2,
    image: "/images/food/cat-food-3.jpg",
    blurb: "Higher protein and fat for the first year. Small kibble, easy weaning.",
  },
  {
    slug: "josera-puppy-125kg",
    name: "Josera Puppy",
    brand: "Josera",
    category: "food",
    petTypes: ["dog"],
    price: 19750,
    unit: "12.5 kg sack",
    stock: 4,
    lowStockAt: 2,
    image: "/images/food/dog-food-2.jpg",
    blurb: "Growth recipe for puppies of small and medium breeds.",
  },
  {
    slug: "munchos-adult-beef-10kg",
    name: "Munchos Adult Beef",
    brand: "Munchos",
    category: "food",
    petTypes: ["dog"],
    price: 9800,
    unit: "10 kg sack",
    stock: 8,
    lowStockAt: 3,
    image: "/images/food/dog-food-3.jpg",
    blurb: "The everyday Pakistani dog food. Solid value for guard-dog appetites.",
  },
  {
    slug: "purina-one-lamb-3kg",
    name: "Purina ONE Lamb and Rice",
    brand: "Purina ONE",
    category: "food",
    petTypes: ["dog"],
    price: 6200,
    unit: "3 kg bag",
    stock: 6,
    lowStockAt: 2,
    image: "/images/food/dog-food-4.jpg",
    blurb: "Lamb and rice for dogs with itchy skin on chicken diets.",
  },
  {
    slug: "grain-free-adult-cat-salmon-7kg",
    name: "Grain Free Adult Cat Salmon",
    brand: "Josera",
    category: "food",
    petTypes: ["cat"],
    price: 17500,
    unit: "7 kg sack",
    stock: 2,
    lowStockAt: 2,
    image: "/images/food/cat-food-4.jpg",
    blurb: "No wheat, no corn. Salmon first ingredient for sensitive stomachs.",
  },
  {
    slug: "covid-cat-litter-10l",
    name: "Covid Clumping Cat Litter",
    brand: "Covid",
    category: "litter",
    petTypes: ["cat"],
    price: 1450,
    unit: "10 L bag",
    stock: 14,
    lowStockAt: 5,
    image: "/images/litter/cat-litter-1.jpg",
    blurb: "Bentonite clumping litter, the one most Islamabad cat homes use.",
  },
  {
    slug: "so-phresh-paper-pellets",
    name: "so Phresh Paper Pellet Litter",
    brand: "so Phresh",
    category: "litter",
    petTypes: ["cat", "small-pet"],
    price: 2600,
    unit: "25 L bag",
    stock: 7,
    lowStockAt: 3,
    image: "/images/litter/cat-litter-2.jpg",
    blurb: "Paper pellets, low dust. Kind after surgery or for kittens in transition.",
  },
  {
    slug: "rope-toy-tug-dog",
    name: "Cotton Rope Tug Toy",
    brand: "Happy Tails picks",
    category: "toys",
    petTypes: ["dog"],
    price: 550,
    unit: "one size",
    stock: 18,
    lowStockAt: 6,
    image: "/images/toys/dog-toy-1.jpg",
    blurb: "Three-strand cotton rope for tug and fetch. Flosses teeth while they play.",
  },
  {
    slug: "jingle-balls-cat-4pack",
    name: "Jingle Balls for Cats",
    brand: "Happy Tails picks",
    category: "toys",
    petTypes: ["cat"],
    price: 400,
    unit: "pack of 4",
    stock: 22,
    lowStockAt: 8,
    image: "/images/toys/cat-toy-1.jpg",
    blurb: "Lightweight bells that race across tile floors. The 3 a.m. classic.",
  },
  {
    slug: "cat-teaser-wand-feather",
    name: "Feather Teaser Wand",
    brand: "Happy Tails picks",
    category: "toys",
    petTypes: ["cat"],
    price: 450,
    unit: "60 cm wand",
    stock: 15,
    lowStockAt: 6,
    image: "/images/toys/cat-toy-2.jpg",
    blurb: "Retractable wand with replaceable feathers. Supervised play only.",
  },
  {
    slug: "rubber-chew-bone-dog",
    name: "Rubber Chew Bone",
    brand: "Happy Tails picks",
    category: "toys",
    petTypes: ["dog"],
    price: 700,
    unit: "large",
    stock: 12,
    lowStockAt: 5,
    image: "/images/toys/dog-toy-2.jpg",
    blurb: "Natural rubber bone for strong chewers. Stuff it with peanut butter.",
  },
  {
    slug: "nylabone-dura-chew",
    name: "Nylabone Dura Chew",
    brand: "Nylabone",
    category: "toys",
    petTypes: ["dog"],
    price: 1600,
    unit: "wolf size",
    stock: 9,
    lowStockAt: 4,
    image: "/images/toys/dog-toy-3.jpg",
    blurb: "The original tough chew. Replace once it is worn past the ridges.",
  },
  {
    slug: "catnip-mouse-2pack",
    name: "Catnip Mouse",
    brand: "Happy Tails picks",
    category: "toys",
    petTypes: ["cat"],
    price: 350,
    unit: "pack of 2",
    stock: 20,
    lowStockAt: 8,
    image: "/images/toys/cat-toy-3.jpg",
    blurb: "Filled with dried catnip. Expect immediate possession disputes.",
  },
  {
    slug: "padded-leash-15m",
    name: "Padded Dog Leash",
    brand: "Happy Tails picks",
    category: "accessories",
    petTypes: ["dog"],
    price: 900,
    unit: "1.5 m",
    stock: 16,
    lowStockAt: 6,
    image: "/images/accessories/dog-leash-1.jpg",
    blurb: "Nylon leash with a padded handle. Brass-style heavy snap hook.",
  },
  {
    slug: "adjustable-collar-red",
    name: "Adjustable Collar",
    brand: "Happy Tails picks",
    category: "accessories",
    petTypes: ["dog"],
    price: 600,
    unit: "M size",
    stock: 14,
    lowStockAt: 6,
    image: "/images/accessories/dog-collar-1.jpg",
    blurb: "Quick-release clip collar. Fit two fingers under it, no tighter.",
  },
  {
    slug: "ceramic-cat-bowl-set",
    name: "Ceramic Bowl Set",
    brand: "Happy Tails picks",
    category: "accessories",
    petTypes: ["cat", "dog"],
    price: 1200,
    unit: "set of 2",
    stock: 10,
    lowStockAt: 4,
    image: "/images/accessories/pet-bowl-1.jpg",
    blurb: "Two stoneware bowls on a no-spill stand. Dishwasher safe.",
  },
  {
    slug: "cat-carrier-top-load",
    name: "Top Load Pet Carrier",
    brand: "Happy Tails picks",
    category: "accessories",
    petTypes: ["cat", "small-pet"],
    price: 3400,
    oldPrice: 3900,
    unit: "up to 6 kg",
    stock: 5,
    lowStockAt: 2,
    image: "/images/accessories/pet-carrier-1.jpg",
    blurb: "Hard-shell carrier that opens from the top. Calmer vet visits.",
  },
  {
    slug: "dog-bed-square-fleece",
    name: "Fleece Dog Bed",
    brand: "Happy Tails picks",
    category: "accessories",
    petTypes: ["dog", "cat"],
    price: 4200,
    unit: "L size",
    stock: 4,
    lowStockAt: 2,
    image: "/images/accessories/pet-bed-1.jpg",
    blurb: "Bolster-sided bed with a washable cover. Winter favourite.",
  },
  {
    slug: "cat-scratcher-cardboard",
    name: "Cardboard Cat Scratcher",
    brand: "Happy Tails picks",
    category: "accessories",
    petTypes: ["cat"],
    price: 850,
    unit: "with catnip",
    stock: 13,
    lowStockAt: 5,
    image: "/images/accessories/cat-scratcher-1.jpg",
    blurb: "Corrugated lounge scratcher. Cheaper than a new sofa.",
  },
  {
    slug: "grooming-slicker-brush",
    name: "Slicker Brush",
    brand: "Happy Tails picks",
    category: "grooming",
    petTypes: ["dog", "cat"],
    price: 750,
    unit: "medium",
    stock: 11,
    lowStockAt: 4,
    image: "/images/grooming/slicker-brush-1.jpg",
    blurb: "Fine wire pins lift loose undercoat. Go gentle on short coats.",
  },
  {
    slug: "nail-clipper-guillotine",
    name: "Guillotine Nail Clipper",
    brand: "Happy Tails picks",
    category: "grooming",
    petTypes: ["dog", "cat"],
    price: 650,
    unit: "one size",
    stock: 10,
    lowStockAt: 4,
    image: "/images/grooming/nail-clipper-1.jpg",
    blurb: "Sharp small clipper for nails. Ask us to show you the quick.",
  },
  {
    slug: "pet-shampoo-oatmeal-500",
    name: "Oatmeal Pet Shampoo",
    brand: "Happy Tails picks",
    category: "grooming",
    petTypes: ["dog", "cat"],
    price: 1100,
    unit: "500 ml",
    stock: 9,
    lowStockAt: 4,
    image: "/images/grooming/shampoo-1.jpg",
    blurb: "Tear-free oatmeal wash for itchy skin. Not for cats under 12 weeks.",
  },
  {
    slug: "deshedding-glove",
    name: "Deshedding Glove",
    brand: "Happy Tails picks",
    category: "grooming",
    petTypes: ["cat", "dog"],
    price: 800,
    unit: "one size",
    stock: 12,
    lowStockAt: 5,
    image: "/images/grooming/brush-1.jpg",
    blurb: "Silicone-tipped glove. Cats think it is petting, not grooming.",
  },
  {
    slug: "dewormer-suspension-20ml",
    name: "Deworming Suspension",
    brand: "Beaphar",
    category: "pharmacy",
    petTypes: ["dog", "cat"],
    price: 950,
    unit: "20 ml",
    stock: 8,
    lowStockAt: 4,
    image: "/images/pharmacy/dewormer-1.jpg",
    blurb: "Broad-spectrum wormer. Dose by weight, repeat at 14 days.",
  },
  {
    slug: "tick-flea-spot-on-3pip",
    name: "Tick and Flea Spot On",
    brand: "Beaphar",
    category: "pharmacy",
    petTypes: ["dog", "cat"],
    price: 1400,
    unit: "3 pipettes",
    stock: 7,
    lowStockAt: 3,
    image: "/images/pharmacy/spoton-1.jpg",
    blurb: "Monthly spot-on for ticks and fleas. Split by weight classes.",
  },
  {
    slug: "calcium-syrup-200ml",
    name: "Calcium Syrup",
    brand: "Happy Tails pharmacy",
    category: "pharmacy",
    petTypes: ["dog", "cat"],
    price: 1200,
    unit: "200 ml",
    stock: 6,
    lowStockAt: 3,
    image: "/images/pharmacy/supplement-1.jpg",
    blurb: "For growing pups and nursing mothers. Vet will set the dose.",
  },
  {
    slug: "vitamin-paste-kitten-100g",
    name: "Kitten Vitamin Paste",
    brand: "Beaphar",
    category: "pharmacy",
    petTypes: ["cat"],
    price: 1350,
    unit: "100 g tube",
    stock: 5,
    lowStockAt: 3,
    image: "/images/pharmacy/paste-1.jpg",
    blurb: "Malt paste with vitamins. Most kittens lick the tube itself.",
  },
  {
    slug: "anti-tick-powder-100g",
    name: "Anti Tick Powder",
    brand: "Happy Tails pharmacy",
    category: "pharmacy",
    petTypes: ["dog", "cat"],
    price: 500,
    unit: "100 g",
    stock: 9,
    lowStockAt: 4,
    image: "/images/pharmacy/powder-1.jpg",
    blurb: "Dust through the coat after baths, avoid eyes and nose.",
  },
  {
    slug: "wound-spray-antiseptic",
    name: "Antiseptic Wound Spray",
    brand: "Happy Tails pharmacy",
    category: "pharmacy",
    petTypes: ["dog", "cat", "bird"],
    price: 850,
    unit: "100 ml",
    stock: 7,
    lowStockAt: 3,
    image: "/images/pharmacy/spray-1.jpg",
    blurb: "For small cuts and hot spots. If it is deep, come straight in.",
  },
];
